apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  selector:
    matchLabels:
      app: web
      tier: web_micro
      track: stable
  template:
    metadata:
      labels:
        app: web
        tier: web_micro
        track: stable
    spec:
      containers:
        - name: web
          imagePullPolicy: Never
          image: web:latest
          ports:
            - name: http
              containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  type: NodePort
  selector:
    app: web
    tier: example
  ports:
    - protocol: TCP
      port: 3000
      targetPort: http
      nodePort: 32000