apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  selector:
    matchLabels:
      run: api
  replicas: 2
  template:
    metadata:
      labels:
        run: api
    spec:
      containers:
        - name: api
          image: api_micro:latest
          ports:
            - name: http
              containerPort: 3030
---
apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    run: api
spec:
  type: NodePort
  selector:
    app: api
    tier: example
  ports:
    - protocol: TCP
      port: 3030
      targetPort: http
      nodePort: 30300